### ISSUE TITLE
Create github workflow for release.yaml for auger project 

### ISSUE THREAD

**Issue by haiwu** [etcd-io/auger#28]
Right now, there's only one released tag for this project from back year 2019, which is outdated. 

Please create new github workflow for release.yaml for auger project, similar to https://github.com/etcd-io/etcd/blob/main/.github/workflows/release.yaml, and please release some latest version for auger based on that.

**Comment by bavarianbidi** [comment]
:raising_hand: for volunteering on this. 
As i often use `go-releaser` for such topics and [`release.sh`](https://github.com/etcd-io/etcd/blob/main/scripts/release.sh) from [etcd repo](https://github.com/etcd-io/etcd) seems like a bash-like re-implementation of go-releaser i could make a proposal to use go-releaser instead of the `release.sh` script.

This could be also seen as blueprint for releasing `etcd` with go-releaser (if needed)

**Comment by jmhbnz** [comment]
Hi @bavarianbidi - Many thanks for volunteering to help with this, please feel free draft a pull request. 

/assign @bavarianbidi

**Comment by bavarianbidi** [comment]
just stumbled over https://github.com/etcd-io/etcd/issues/18604
we should probably wait once there is a decision and either go ahead with `goreleaser` or switch to the `etcd-io/etcd` implementation.

**Comment by ivanvc** [comment]
Hi @bavarianbidi, I don't think you should wait for a decision on https://github.com/etcd-io/etcd/issues/18604. In my opinion, auger is a smaller project and a great fit for `goreleaser`.
